name: deploy

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@main

            - name: Build and Deploy
              uses: ./.github/actions/deploy
              env:
                  COMMIT_EMAIL: dan@tate.nz
                  COMMIT_NAME: dan
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BASE_BRANCH: main
                  DEPLOY_BRANCH: gh-pages
                  BUILD_SCRIPT: npm && npm build
                  FOLDER: build
